[package]
name = "susblast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbase = "0.4.0"
explode = "0.1.2"
suppaftp = "5.2.0"
